config/routes.rb
Rails.application.routes.draw do
  

root 'photos#newsfeed'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do 
    resources :photos
end

devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy' 
end

  resources :photos do
    resources :comments 
  end
  resources :users do
  	resources :comments
  end

 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :photo
	belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :photos
  has_many :comments

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
  end
	
	 def destroy
   @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
    @comment.destroy
    redirect_to photo_path(@photo)
  end	

  def edit
  	@photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
  end

  def update
  	@photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to photo_path(@photo)
    else 
      render 'edit'
    end
  end


private
def comment_params
	params.require(:comment).permit(:body)
end



end 

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
	 @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!, :except => [:index, :show]
	def newsfeed
		@photos = Photo.all
	end

	def index
		@photos = current_user.photos.all 
	end 
	def new
		@photo = Photo.new
	end
	def show
		@photo = Photo.find params[:id]
	end

	def edit
		@photo = Photo.find params[:id]
	end

	def create
		@photo = current_user.photos.new(photo_params)
		if @photo.save
			redirect_to @photo
		else
			render 'new'
		end
	end

	def update
		@photo = Photo.find(params[:id])

		if @photo.update(photo_params)
			redirect_to @photo
		else 
			render 'edit'
		end
	end

	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy

		redirect_to photos_path
	end

	private
	def photo_params
	params.require(:photo).permit(:public,:caption, :image)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<% if current_user.id == comment.user_id %>
<%= link_to 'Edit', edit_photo_comment_path(comment.photo, comment) %>
  <%= link_to 'Delete', [comment.photo, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% end %>

</p>

app/views/comments/_form.html.erb
<%= form_for([@photo, @comment]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_path(@photo) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
  <%= form_for @photo do |f| %>
  <h1> New Photo </h1>

  <p>
    <%= f.label :public %><br>
    <%= f.text_field :public %>
  </p>
 
  <p>
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </p>

   <p>
    <%= f.label :caption %><br>
    <%= f.text_area :caption %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

  <% end %>
 

app/views/photos/edit.html.erb
<h1>Editing photo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1> My Photos </h1>
<%= link_to 'New Photo', new_photo_path %>

<% @photos.each do |photo| %>

<p> <img src="<%= photo.image %>"></p>
<h2> <%= photo.caption %></h2>
<p><%= link_to "Show", photo_path(photo) %></p>

<% end %>

app/views/photos/new.html.erb
<h1>Editing photo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', photos_path %>

app/views/photos/newsfeed.html.erb
<h1> Welcome to BruGram </h1>
<%= link_to 'My Photos', photos_path %>

<% @photos.each do |photo| %>

<% if photo.public == true || User.find(photo.user_id) == current_user %>
<h2> by: <%= photo.user.email %> </h2>
<p> <img src="<%= photo.image %>"></p>
<h2> <%= photo.caption %></h2>
<p><%= link_to "Show", photo_path(photo) %></p>

<% end %>
<% end %>

app/views/photos/show.html.erb
<br>
<br>
<img src="<%= @photo.image %>">
 
<h2>
  <%= @photo.caption %>
</h2>

<% if User.find(@photo.user_id) == current_user %>
<%= link_to 'Edit', edit_photo_path(@photo) %> 
<%= link_to 'Delete', (@photo),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<% end %>

<h2>Comments</h2>
<%= render @photo.comments %>


<h2>Add a comment:</h2>

<% @comment = Comment.new %>
<%= render 'comments/form' %>


<%= link_to 'Back', root_path %>